### ISSUE TITLE
Calendar events are not showed on calendar default app after to registered

### ISSUE THREAD

**Issue by fpuebla** [belatrix/BelatrixEventsAndroid#4]
Steps:

login into the app
Tap on any Event
Register to the Event
Verify it into Calendar Default App

Expected:
Event should be displayed into Calendar Default App

Actual:
Calendar events are not showed on calendar default app after to registered

**Comment by carlosmonzon** [comment]
bug fixed in development

**Comment by fpuebla** [comment]
This issue is still happening Only in Android 7. 
Tested on Motorola G4 Plus Android 7, Samsung S5(GT-I9506) Android 4.4.2, Nexus 5 Android 5.1.1, Nexus 7 Android 6.0.0
